version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test-db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  postgres-data:
  mysql-data:
