name: ci
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  build-test-lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [lts/*]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test
